import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tang
 */
public class AddJobForm extends javax.swing.JFrame {
    CompanyMainForm companyMainForm = new CompanyMainForm();
    AddJobService addJobService = new AddJobService();
    /**
     * Creates new form Register_Job
     */
    public AddJobForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        regisform = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        box_jobtype = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_property = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_detail = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        box_province = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_welfare = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        addJobDetail = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        area_work = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regisform.setBackground(new java.awt.Color(255, 255, 255));
        regisform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        regisform.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1250, 10, 40));

        jLabel11.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("สวัสดิการ (กรอกเป็นข้อๆ)");
        regisform.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1090, -1, 30));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                       เพิ่มตำแหน่งงาน");
        jLabel3.setToolTipText("");
        jLabel3.setOpaque(true);
        regisform.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel2.setText("     ประกาศ");
        regisform.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 31));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel4.setText("> บริษัทที่เข้าข่ายหลอกลวง ประกาศตำแหน่งไม่ตรงกับที่รับ หรือ เรียกนัดสัมภาษณ์ โดยไม่ระบุตำแหน่งอย่างชัดเจน");
        regisform.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 580, 30));

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel5.setText("ถ้าทางเราตรวจสอบพบจะทำการระงับการให้บริการในทันที พร้อมทั้งทำการแจ้งหน่วยงานที่รับผิดชอบเข้าไปตรวจสอบ ");
        regisform.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 30));

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel6.setText("และดําเนินการตามกฎหมายทันที");
        regisform.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel7.setText("> ไม่อนุญาติให้ลงตำแหน่งงาน ใน ประเภทของงาน ที่ไม่มีความเกี่ยวข้องกับตำแหน่งงาน เช่น พนักงานขาย");
        regisform.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 580, 20));

        jLabel8.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel8.setText("จะไม่สามารถลงใน ประเภทงาน บัญชี ได้ หากลงไม่ตรงประเภท ทางบริษัทขอสงวน สิทธิ์ในการแก้ไข");
        regisform.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel9.setText("ประเภทของงาน ตามความเหมาะสม");
        regisform.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("ชื่อตำแหน่ง");
        regisform.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 30));

        jLabel17.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        regisform.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 10, 30));

        box_jobtype.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        box_jobtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "เลือกประเภทงาน", "กฎหมาย", "เกษตร/ปศุสัตว์/ประมง/เหมืองแร่\t  ", "เจ้าหน้าที่ขาย-การตลาด/พนักงานขาย-การตลาด", "ประสานงานการขาย-การตลาด", "ผู้จัดการ/ผู้ช่วยผู้จัดการขาย-การตลาด\t   ", "งานการศึกษา/นักวิชาการ/อาจารย์", "ธุรการ/ประสานงาน/คีย์ข้อมูล\t   ", "เลขานุการ\t   ", "ประชาสัมพันธ์/บริการลูกค้า", "บัญชี/การเงิน-การธนาคาร\t   ", "บุคคล/ฝึกอบรม/Training\t   ", "จัดซื้อ/คลังสินค้า/logistics", "นำเข้า/ ส่งออก/ Shipping", "งานด้านต่างประเทศ\t   ", "โรงงาน/การผลิต/ควบคุมคุณภาพ\t   ", "ช่างยนต์/ช่างกลโรงงาน/ช่างเทคนิคอุตสาหกรรม", "ช่างไฟฟ้า/ช่างอิเลกทรอนิกส์/ช่างโลหะ\t   ", "ช่างคอมพิวเตอร์/ช่างเทคนิคคอมพิวเตอร์\t   ", "ช่างจิวเวอร์รี่ /ช่างทอง-เงิน", "ดีไซด์เนอร์/ช่างตัดเย็บเสื้อผ้า/ช่างแพทเทิร์น\t   ", "โฟร์แมน/ช่างก่อสร้าง/ช่างไม้", "งานเขียนแบบ/ งานDrawing", "ศิลปะ/จิตรกรรม/ออกแบบผลิตภัณฑ์\t   ", "Programmer/System Admin/IT\t ", "Web programmer/Webmaster", "Web Design/Graphic Design", "วิศวกรขาย/Sale Engineer", "วิศวกรเครื่องกล/โรงงาน/วิศวกรอุตสาหกรรม", "วิศวกรไฟฟ้า/วิศวกรอิเลกทรอนิกส์\t  ", "วิศวกรโยธา/วิศวกรก่อสร้าง\t   ", "วิศวกรสื่อสาร/โทรคมนาคม", "วิศวกรคอมพิวเตอร์/วิศวกรระบบ ", "สถาปัตยกรรม/ออกแบบตกแต่ง/ประเมินราคา\t   ", "งานโฆษณา/ขายโฆษณา/Creative/ช่างภาพ", "งานบันเทิง/ นักแสดง/ พริ๊ตตี้/ นักดนตรี/ นักร้อง  ", "สุขภาพความงาม/เสริมสวย/สปา/ฟิตเนส\t   ", "ผู้จัดการทั่วไป/ผู้อำนวยการ/งานผู้บริหาร", "พัฒนาธุรกิจ/พัฒนาองค์กร ISO", "เศรษฐศาสตร์/สถิติ/งานวิจัย/หุ้น/การประกันภัย  ", "นักข่าว/บรรณาธิการ/นักเขียน/แปลภาษา", "การโรงแรม/ล่าม/ไกด์/มัคคุเทศก์/งานท่องเที่ยว ", "งานบริการทั่วไป/บริกร/พนักงานเสิร์ฟ\t  ", "งานด้านอาหาร-เครื่องดื่ม/กุ๊ก/บาร์เทนเดอร์", "แพทย์/พยาบาล/เภสัช\t   ", "วิทยาศาสตร์/เคมี/ชีวะ/สิ่งแวดล้อม/ภูมิศาสตร์\t  ", "วิทยาศาสตร์อาหาร/โภชนาการ", "เจ้าหน้าที่ความปลอดภัยวิชาชีพ(จป.วิชาชีพ)\t   ", "ส่งเอกสาร/ส่งผลิตภัณฑ์/ขับรถ/แม่บ้าน/รปภ.\t   ", "งาน Part-time/นักศึกษาฝึกงาน" }));
        box_jobtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_jobtypeActionPerformed(evt);
            }
        });
        regisform.add(box_jobtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 580, 40));

        jLabel13.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("ประเภทงาน");
        regisform.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 30));

        jLabel18.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        regisform.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 10, 30));

        name.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        regisform.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 580, 40));

        jLabel14.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("จำนวนที่รับ (อัตรา)");
        regisform.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 30));

        jLabel19.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        regisform.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 10, 30));

        amount.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        regisform.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 580, 40));

        jLabel15.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("เงินเดือน (โดยประมาณ)");
        regisform.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, 30));

        jLabel20.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        regisform.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 10, 30));

        area_property.setColumns(20);
        area_property.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        area_property.setRows(5);
        jScrollPane1.setViewportView(area_property);

        regisform.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 580, 150));

        jLabel21.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("ลักษณะงาน (อธิบายสั้นๆ)");
        regisform.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 170, 30));

        jLabel22.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        regisform.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 10, 30));

        area_detail.setColumns(20);
        area_detail.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        area_detail.setRows(5);
        jScrollPane2.setViewportView(area_detail);

        regisform.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 580, 140));

        jLabel23.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("คุณสมบัติของผู้สมัคร (กรอกเป็นข้อๆ)");
        regisform.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 250, 30));

        jLabel24.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        regisform.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 680, 10, 30));

        salary.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        regisform.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 580, 40));

        jLabel25.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 153));
        jLabel25.setText("สถานที่ปฏิบัติงาน");
        regisform.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, 120, 30));

        jLabel26.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        regisform.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 860, 10, 30));

        box_province.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        box_province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "เลือกจังหวัด", "กรุงเทพมหานคร ", "กระบี่ ", "กาญจนบุรี ", "กาฬสินธุ์ ", "กำแพงเพชร ", "ขอนแก่น ", "จันทบุรี ", "ฉะเชิงเทรา ", "ชลบุรี ", "ชัยนาท ", "ชัยภูมิ ", "ชุมพร ", "เชียงราย ", "เชียงใหม่ ", "ตรัง ", "ตราด ", "ตาก ", "นครนายก ", "นครปฐม ", "นครพนม ", "นครราชสีมา ", "นครศรีธรรมราช ", "นครสวรรค์ ", "นนทบุรี ", "นราธิวาส ", "น่าน ", "บึงกาฬ ", "บุรีรัมย์ ", "ปทุมธานี ", "ประจวบคีรีขันธ์ ", "ปราจีนบุรี ", "ปัตตานี ", "พระนครศรีอยุธยา ", "พังงา ", "พัทลุง ", "พิจิตร ", "พิษณุโลก ", "เพชรบุรี ", "เพชรบูรณ์ ", "แพร่ ", "พะเยา ", "ภูเก็ต ", "มหาสารคาม ", "มุกดาหาร ", "แม่ฮ่องสอน ", "ยะลา ", "ยโสธร ", "ร้อยเอ็ด ", "ระนอง ", "ระยอง ", "ราชบุรี ", "ลพบุรี ", "ลำปาง ", "ลำพูน ", "เลย ", "ศรีสะเกษ ", "สกลนคร ", "สงขลา ", "สตูล ", "สมุทรปราการ ", "สมุทรสงคราม ", "สมุทรสาคร ", "สระแก้ว ", "สระบุรี ", "สิงห์บุรี ", "สุโขทัย ", "สุพรรณบุรี ", "สุราษฎร์ธานี ", "สุรินทร์ ", "หนองคาย ", "หนองบัวลำภู ", "อ่างทอง ", "อุดรธานี ", "อุทัยธานี ", "อุตรดิตถ์ ", "อุบลราชธานี ", "อำนาจเจริญ" }));
        regisform.add(box_province, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1050, 580, 40));

        jLabel27.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("จังหวัดที่ปฏิบัติงาน");
        regisform.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1020, 130, 30));

        jLabel28.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");
        regisform.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1090, 10, 30));

        area_welfare.setColumns(20);
        area_welfare.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        area_welfare.setRows(5);
        jScrollPane3.setViewportView(area_welfare);

        regisform.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1120, 580, 140));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel1.setText("หมายเหตุ : ช่องที่มี       หมายความว่าจำเป็นต้องกรอกข้อมูล");
        regisform.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1260, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jToggleButton1.setText("ยกเลิก");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 280, 40));

        addJobDetail.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        addJobDetail.setText("จัดเก็บข้อมูล");
        addJobDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJobDetailActionPerformed(evt);
            }
        });
        jPanel1.add(addJobDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        regisform.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1290, 580, 90));

        area_work.setColumns(20);
        area_work.setRows(5);
        jScrollPane5.setViewportView(area_work);

        regisform.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 890, 580, 130));

        jLabel29.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");
        regisform.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1020, 10, 30));

        jScrollPane4.setViewportView(regisform);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void addJobDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJobDetailActionPerformed
        String jobName = name.getText();
        String jobType = box_jobtype.getSelectedItem().toString();
        String jobAmount = amount.getText();
        String jobSalary = salary.getText();
        String jobDetail = area_detail.getText().toString();
        String jobProperty = area_property.getText().toString();
        String jobAddress = area_work.getText();
        String province = box_province.getSelectedItem().toString();
        String jobWelfare = area_welfare.getText().toString();
        
        if (!addJobService.checkJobBlank(jobName, jobType, jobAmount, jobSalary, jobDetail, jobProperty, 
                                        jobAddress, province, jobWelfare)) {
            JOptionPane.showMessageDialog(null, "กรุณากรอกข้อมูลให้ครบ", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!addJobService.checkTypeJobName(jobName)) {
            JOptionPane.showMessageDialog(null, "กรอกข้อมูลไม่ถูกต้อง", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!addJobService.checkTypeJobAmount(jobAmount)) {
            JOptionPane.showMessageDialog(null, "กรอกข้อมูลไม่ถูกต้อง", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!addJobService.checkTypeJobSalary(jobSalary)) {
            JOptionPane.showMessageDialog(null, "กรอกข้อมูลไม่ถูกต้อง", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            addJobService.insertJob(jobName, jobType, jobAmount, jobSalary, jobDetail, jobProperty, jobAddress, province, jobWelfare);
            //companyMainForm.setJobList(addJobService.getUsername());
            JOptionPane.showMessageDialog(null, "เพิ่มตำแหน่งงานสำเร็จ");
            this.hide();
            companyMainForm.setJobList(addJobService.getUsername());
            companyMainForm.show();
        }
    }//GEN-LAST:event_addJobDetailActionPerformed

    private void box_jobtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_jobtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_jobtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddJobForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddJobForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddJobForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddJobForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddJobForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addJobDetail;
    private javax.swing.JTextField amount;
    private javax.swing.JTextArea area_detail;
    private javax.swing.JTextArea area_property;
    private javax.swing.JTextArea area_welfare;
    private javax.swing.JTextArea area_work;
    private javax.swing.JComboBox<String> box_jobtype;
    private javax.swing.JComboBox<String> box_province;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField name;
    private javax.swing.JPanel regisform;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
