
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tang
 */
public class ApplicantListForm extends javax.swing.JFrame {
    ApplicantListService applicantListService = new ApplicantListService();
    ArrayList<Applicant> applicantArr = new ArrayList<>();
    /**
     * Creates new form ApplicantListForm
     */
    public ApplicantListForm() {
        initComponents();
    }
    
    public void setApplicantList(String jobName) {
        DefaultListModel applicantList = new DefaultListModel();
        
        applicantArr = applicantListService.getApplicantListByJobName(jobName);
        
        for (int i = 0 ; i < applicantArr.size() ; i++) {
            applicantList.addElement(applicantArr.get(i).name);
        }
        list_applicantList.setModel(applicantList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_applicantList = new javax.swing.JList<>();
        btn_back = new javax.swing.JButton();
        btn_showApplicantDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                            รายชื่อผู้สมัครงาน");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        list_applicantList.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(list_applicantList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, 330));

        btn_back.setBackground(new java.awt.Color(153, 0, 0));
        btn_back.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("กลับ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 200, 40));

        btn_showApplicantDetail.setBackground(new java.awt.Color(153, 0, 0));
        btn_showApplicantDetail.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_showApplicantDetail.setForeground(new java.awt.Color(255, 255, 255));
        btn_showApplicantDetail.setText("ดูข้อมูล");
        btn_showApplicantDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showApplicantDetailActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showApplicantDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.hide();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_showApplicantDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showApplicantDetailActionPerformed
        ApplicantDetailForm applicantDetail = new ApplicantDetailForm();
        try {
            String applicantName = list_applicantList.getSelectedValue().toString();
            ArrayList<Applicant> applicantSelect = new ArrayList<>();
            for (int i = 0 ; i < applicantArr.size() ; i++) {
                if (applicantName.equals(applicantArr.get(i).name)) {
                    applicantSelect.add(applicantArr.get(i));
                    applicantDetail.setApplicant(applicantName, applicantSelect);
                    applicantDetail.show();
                    break;
                }
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "กรุณาเลือกงานที่ต้องการ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_showApplicantDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_showApplicantDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_applicantList;
    // End of variables declaration//GEN-END:variables
}
