
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tang
 */
public class CompanyMainForm extends javax.swing.JFrame {
     ArrayList<Job> job = new ArrayList<>();
     CompanyMainService companyMainService = new CompanyMainService();
     
    /**
     * Creates new form CompanyMainForm
     */
    public CompanyMainForm() {
        
        initComponents();
    }
    
    public void setJobList(String username) {
        DefaultListModel jobList = new DefaultListModel();
        job = companyMainService.getJobByUsername(username);
        
        for (int i = 0 ; i < job.size() ; i++) {
            jobList.addElement(job.get(i).jobName);
        }
        list_jobList.setModel(jobList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_jobList = new javax.swing.JList<>();
        btn_refresh = new javax.swing.JButton();
        btn_showApplicant = new javax.swing.JButton();
        btn_addJob = new javax.swing.JButton();
        btn_disconnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                                หน้าหลัก");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        list_jobList.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(list_jobList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, 330));

        btn_refresh.setBackground(new java.awt.Color(153, 0, 0));
        btn_refresh.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("รีเฟรช");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 200, 40));

        btn_showApplicant.setBackground(new java.awt.Color(153, 0, 0));
        btn_showApplicant.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_showApplicant.setForeground(new java.awt.Color(255, 255, 255));
        btn_showApplicant.setText("ดูใบสมัคร");
        btn_showApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showApplicantActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showApplicant, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, 40));

        btn_addJob.setBackground(new java.awt.Color(153, 0, 0));
        btn_addJob.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_addJob.setForeground(new java.awt.Color(255, 255, 255));
        btn_addJob.setText("เพิ่มตำแหน่งงาน");
        btn_addJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addJobActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 200, 40));

        btn_disconnect.setBackground(new java.awt.Color(153, 0, 0));
        btn_disconnect.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_disconnect.setForeground(new java.awt.Color(255, 255, 255));
        btn_disconnect.setText("ออกจากระบบ");
        btn_disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disconnectActionPerformed(evt);
            }
        });
        jPanel1.add(btn_disconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addJobActionPerformed
        AddJobForm addJob = new AddJobForm();
        addJob.show();
        hide();
    }//GEN-LAST:event_btn_addJobActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        setJobList(companyMainService.getUsername());
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_showApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showApplicantActionPerformed
        ApplicantListForm applicantListForm = new ApplicantListForm();
        try {
            String jobName = list_jobList.getSelectedValue().toString();
            applicantListForm.setApplicantList(jobName);
            applicantListForm.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "กรุณาเลือกงานที่ต้องการ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_showApplicantActionPerformed

    private void btn_disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disconnectActionPerformed
        companyMainService.logout();
        LoginForm login = new LoginForm();
        login.show();
        hide();
    }//GEN-LAST:event_btn_disconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addJob;
    private javax.swing.JButton btn_disconnect;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_showApplicant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_jobList;
    // End of variables declaration//GEN-END:variables
}
