import com.mongodb.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tang
 */
public class RegisterCompanyForm extends javax.swing.JFrame {
    /**
     * Creates new form Register_Company
     */
    RegisterCompanyService register = new RegisterCompanyService();
    Database data = new Database();
    public RegisterCompanyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        registerform = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_rePasword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        box_businesstype = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_tellnumber = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_contactname = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_companyDetail = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_companyname = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        box_province = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_zipcode = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        nevigator1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JToggleButton();
        accept = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerform.setBackground(new java.awt.Color(255, 255, 255));
        registerform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form.setBackground(new java.awt.Color(204, 204, 204));
        form.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    Step 2 : ข้อมูลบริษัท");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);
        form.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 540, 40));

        jLabel10.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");
        form.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1050, 10, 40));

        jLabel11.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Username ");
        form.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jLabel12.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        form.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 10, 30));
        form.add(txt_rePasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 350, 40));

        jLabel13.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Password");
        form.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 30));

        jLabel14.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        form.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 10, 30));
        form.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 350, 40));

        jLabel15.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Re-Password");
        form.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));

        jLabel16.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        form.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 10, 30));
        form.add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 350, 40));

        jLabel17.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Email");
        form.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, 30));

        jLabel18.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        form.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 10, 30));
        form.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 350, 40));

        jLabel19.setBackground(new java.awt.Color(153, 0, 0));
        jLabel19.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("    Step 1 : ข้อมูลการเข้าสู่ระบบ");
        jLabel19.setToolTipText("");
        jLabel19.setOpaque(true);
        form.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        jLabel20.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("เบอร์โทรศัพท์");
        form.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 30));

        jLabel21.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        form.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 10, 30));

        box_businesstype.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        box_businesstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "เลือกประเภทธุรกิจ", "ธุรกิจการโฆษณา", "ธุรกิจการเกษตร", "ธุรกิจยานยนต์", "ธุรกิจธนาคาร", "ธุรกิจการเคมี-พลาสติก", "ธุรกิจการคอมพิวเตอร์", "ธุรกิจก่อสร้าง-วัสดุก่อสร้าง", "ธุรกิจที่ปรึกษา", "ธุรกิจออกแบบ-ตกแต่ง", "ธุรกิจการศึกษา", "ธุรกิจอุตสาหกรรมไฟฟ้า", "ธุรกิจอุตสาหกรรมอิเล็คโทรนิค", "ธุรกิจพลังงาน", "ธุรกิจบันเทิง", "ธุรกิจสถาบันการเงิน-สินเชื่อ-บัตรเครดิต", "ธุรกิจอาหาร-เครื่องดื่ม", "ธุรกิจเสื้อผ้า-สิ่งทอ", "ราชการ/รัฐวิสาหกิจ/มูลนิธิ/องค์กร", "ธุรกิจโรงพยาบาล/เครื่องมือแพทย์", "ธุรกิจโรงแรม-รีสอร์ท", "ธุรกิจนำเข้า-ส่งออก", "ธุรกิจประกันชีวิต-ประกันภัย", "ธุรกิจเครื่องประดับ-อัญมณี", "ธุรกิจยา/เครื่องสำอาง", "ธุรกิจบรรจุภัณฑ์", "ธุรกิจเครื่องเขียน-กระดาษ", "ธุรกิจสิ่งพิมพ์", "ธุรกิจอสังหาริมทรัพย์", "ธุรกิจจัดหางาน", "ธุรกิจค้าปลีก", "ธุรกิจบริการ", "ธุรกิจสื่อสารและโทรคมนาคม", "ธุรกิจขนส่ง", "ธุรกิจการท่องเที่ยว", "ธุรกิจศูนย์สรรพสินค้า", "ธุรกิจกฎหมาย", "ธุรกิจอุตสาหกรรมโลหะ/เหล็ก", "ธุรกิจไม้/เฟอร์นิเจอร์/เครื่องใช้", "ธุรกิจสื่อสารมวลชน", "ธุรกิจขายตรง /MLM", "ธุรกิจจำหน่ายเสื้อผ้า/อุปกรณ์กีฬา", "ธุรกิจอื่นๆ\t\t" }));
        box_businesstype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_businesstypeActionPerformed(evt);
            }
        });
        form.add(box_businesstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 500, 40));

        jLabel22.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("ประเภทของธุรกิจ");
        form.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 30));

        jLabel23.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("*");
        form.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 10, 30));
        form.add(txt_tellnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 350, 40));

        jLabel24.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 153));
        jLabel24.setText("ชื่อผู้ติดต่อ");
        form.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 70, 30));

        jLabel25.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        form.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 10, 30));
        form.add(txt_contactname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 500, 40));

        jLabel26.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 153));
        jLabel26.setText("ชื่อบริษัท");
        form.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 60, 30));

        jLabel27.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        form.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 10, 30));

        txt_companyDetail.setColumns(20);
        txt_companyDetail.setRows(5);
        jScrollPane1.setViewportView(txt_companyDetail);

        form.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 500, -1));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("^ รายละเอียดในที่นี้คือ อธิบาย รายละเอียด การดำเนินงาน หรือ เกี่ยวกับบริษัท ไม่ใช่ตำแหน่งงานว่าง");
        form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, -1, -1));

        jLabel28.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 153));
        jLabel28.setText("รายละเอียดบริษัท");
        form.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 120, 30));

        jLabel29.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");
        form.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 10, 30));
        form.add(txt_companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 500, 40));

        jLabel30.setFont(new java.awt.Font("Angsana New", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("^ กรอกให้ครบทั้ง บ้านเลขที่, ซอย(ถ้ามี), ถนน, เขต, อำเภอ");
        form.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 890, -1, -1));

        jLabel31.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 153));
        jLabel31.setText("ที่อยู่");
        form.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, 30, 30));

        jLabel32.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("*");
        form.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 820, 10, 30));

        box_province.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        box_province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "เลือกจังหวัด", "กรุงเทพมหานคร ", "กระบี่ ", "กาญจนบุรี ", "กาฬสินธุ์ ", "กำแพงเพชร ", "ขอนแก่น ", "จันทบุรี ", "ฉะเชิงเทรา ", "ชลบุรี ", "ชัยนาท ", "ชัยภูมิ ", "ชุมพร ", "เชียงราย ", "เชียงใหม่ ", "ตรัง ", "ตราด ", "ตาก ", "นครนายก ", "นครปฐม ", "นครพนม ", "นครราชสีมา ", "นครศรีธรรมราช ", "นครสวรรค์ ", "นนทบุรี ", "นราธิวาส ", "น่าน ", "บึงกาฬ ", "บุรีรัมย์ ", "ปทุมธานี ", "ประจวบคีรีขันธ์ ", "ปราจีนบุรี ", "ปัตตานี ", "พระนครศรีอยุธยา ", "พังงา ", "พัทลุง ", "พิจิตร ", "พิษณุโลก ", "เพชรบุรี ", "เพชรบูรณ์ ", "แพร่ ", "พะเยา ", "ภูเก็ต ", "มหาสารคาม ", "มุกดาหาร ", "แม่ฮ่องสอน ", "ยะลา ", "ยโสธร ", "ร้อยเอ็ด ", "ระนอง ", "ระยอง ", "ราชบุรี ", "ลพบุรี ", "ลำปาง ", "ลำพูน ", "เลย ", "ศรีสะเกษ ", "สกลนคร ", "สงขลา ", "สตูล ", "สมุทรปราการ ", "สมุทรสงคราม ", "สมุทรสาคร ", "สระแก้ว ", "สระบุรี ", "สิงห์บุรี ", "สุโขทัย ", "สุพรรณบุรี ", "สุราษฎร์ธานี ", "สุรินทร์ ", "หนองคาย ", "หนองบัวลำภู ", "อ่างทอง ", "อุดรธานี ", "อุทัยธานี ", "อุตรดิตถ์ ", "อุบลราชธานี ", "อำนาจเจริญ" }));
        box_province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_provinceActionPerformed(evt);
            }
        });
        form.add(box_province, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 940, 500, 40));

        jLabel33.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 153, 153));
        jLabel33.setText("จังหวัด");
        form.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 910, 50, 30));

        jLabel34.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("*");
        form.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 910, 10, 30));
        form.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, 500, 40));

        jLabel35.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 153));
        jLabel35.setText("รหัสไปรษณีย์");
        form.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 980, 90, 30));

        jLabel36.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("*");
        form.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 980, 10, 30));
        form.add(txt_zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1010, 500, 40));

        jLabel41.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel41.setText("หมายเหตุ : ช่องที่มี      หมายความว่าจำเป็นต้องกรอกข้อมูล");
        form.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1060, -1, -1));

        nevigator1.setBackground(new java.awt.Color(255, 255, 255));
        nevigator1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel9.setText("  คำแนะนำการตั้ง Password");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nevigator1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 30));

        jLabel37.setFont(new java.awt.Font("Angsana New", 0, 16)); // NOI18N
        jLabel37.setText("  หรือตัวเลข 0-9");
        nevigator1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 20));

        jLabel38.setFont(new java.awt.Font("Angsana New", 0, 16)); // NOI18N
        jLabel38.setText("  8 ตัวอักษร");
        nevigator1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 20));

        jLabel39.setFont(new java.awt.Font("Angsana New", 0, 16)); // NOI18N
        jLabel39.setText("  มีความยาวมากกว่าหรือเท่ากับ");
        nevigator1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 150, 20));

        jLabel40.setFont(new java.awt.Font("Angsana New", 0, 16)); // NOI18N
        jLabel40.setText("  เป็นภาษาอังกฤษ a-z, A-Z ");
        nevigator1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 20));

        jLabel42.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel42.setText("  คำแนะนำการตั้ง Username");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nevigator1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jLabel43.setFont(new java.awt.Font("Angsana New", 0, 16)); // NOI18N
        jLabel43.setText("  มีความยาวมากกว่าหรือเท่ากับ");
        nevigator1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 20));

        jLabel44.setFont(new java.awt.Font("Angsana New", 0, 16)); // NOI18N
        jLabel44.setText("  6 ตัวอักษร");
        nevigator1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 20));

        form.add(nevigator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 200));

        registerform.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 540, 1090));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                        สมัครสมาชิก (ผู้ประกอบการ)");
        jLabel3.setToolTipText("");
        jLabel3.setOpaque(true);
        registerform.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        cancel.setText("ยกเลิก");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 250, 40));

        accept.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        accept.setText("ส่งแบบฟอร์ม");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });
        jPanel1.add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        registerform.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1190, 540, 90));

        jScrollPane2.setViewportView(registerform);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_provinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_provinceActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.hide();
    }//GEN-LAST:event_cancelActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
     String username = txt_userName.getText();
     String password = txt_password.getText();
     String rePassword = txt_rePasword.getText();
     String email = txt_email.getText();
     String tellnumber = txt_tellnumber.getText();
     String businessType = box_businesstype.getSelectedItem().toString();
     String contactName = txt_contactname.getText();
     String companyName = txt_companyname.getText();
     String companyDetail = txt_companyDetail.getText();
     String address = txt_address.getText();
     String province = box_province.getSelectedItem().toString();
     String zipcode = txt_zipcode.getText();
     String userType = "Company";
     String userStatus = "offline";
     if(!register.checkNull(username, password, rePassword, email, tellnumber, businessType, contactName, companyName, companyDetail, address, province, zipcode)){
        JOptionPane.showMessageDialog(null, "กรุณากรอกข้อมูลให้ครบ", "Error", JOptionPane.ERROR_MESSAGE);
     }else if(!register.checkUsernameLength(username)){
        JOptionPane.showMessageDialog(null, "Username ต้องมีความยาวมากกว่าหรือเท่ากับ 6 ตัวอักษร", "Error", JOptionPane.ERROR_MESSAGE);
     }else if(!register.checkPasswordLength(password)){
        JOptionPane.showMessageDialog(null, "Password ต้องมีความยาวมากกว่าหรือเท่ากับ 8 ตัวอักษร", "Error", JOptionPane.ERROR_MESSAGE); 
     }else if(!register.checkPasswordForm(password)){
        JOptionPane.showMessageDialog(null, "Password ต้องมีตัวเลขและตัวอักษรผสมกัน", "Error", JOptionPane.ERROR_MESSAGE); 
     }else if(!register.checkPassword(password, rePassword)){
        JOptionPane.showMessageDialog(null, "password ไม่ตรงกัน", "Error", JOptionPane.ERROR_MESSAGE); 
     }else if(!register.checkCompanyRegisterByUsername(username)){
         JOptionPane.showMessageDialog(null, "Username นี้มีผู้ใช้งานแล้ว", "Error", JOptionPane.ERROR_MESSAGE);
     }else{
         data.insertCompany(username, password, email, tellnumber, businessType, contactName, companyName, companyDetail, address, province, zipcode, userType, userStatus);
         JOptionPane.showMessageDialog(null, "สมัครสมาชิกสำเร็จ");
     }
     
     /*else if(!register.checkTypeCompanyname(username)){
        JOptionPane.showMessageDialog(null, "username ไม่ถูกต้อง", "Error", JOptionPane.ERROR_MESSAGE); 
     }*/
    }//GEN-LAST:event_acceptActionPerformed

    private void box_businesstypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_businesstypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_businesstypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCompanyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton accept;
    private javax.swing.JComboBox<String> box_businesstype;
    private javax.swing.JComboBox<String> box_province;
    private javax.swing.JToggleButton cancel;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel nevigator1;
    private javax.swing.JPanel registerform;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextArea txt_companyDetail;
    private javax.swing.JTextField txt_companyname;
    private javax.swing.JTextField txt_contactname;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_rePasword;
    private javax.swing.JTextField txt_tellnumber;
    private javax.swing.JTextField txt_userName;
    private javax.swing.JTextField txt_zipcode;
    // End of variables declaration//GEN-END:variables
}
