/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class UserMainForm extends javax.swing.JFrame {
    JobListForm jobList = new JobListForm();
    UserMainService userMainService = new UserMainService();
    /**
     * Creates new form workType1
     */
    public UserMainForm() {
        initComponents();
        panel_SearchByJobType.setVisible(true);
        panel_SearchByCompanyName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_SearchByCompanyName = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txt_CompanyName = new javax.swing.JTextField();
        btn_Searchbtn = new javax.swing.JButton();
        panel_SearchByJobType = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        btn_disconnect = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_SearchByCompanyName.setBackground(new java.awt.Color(255, 255, 255));
        panel_SearchByCompanyName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("ค้นหางานตามชื่องาน");
        panel_SearchByCompanyName.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        jLabel60.setBackground(new java.awt.Color(0, 204, 204));
        jLabel60.setOpaque(true);
        panel_SearchByCompanyName.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        jLabel62.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel62.setText("กรอกชื่องาน");
        panel_SearchByCompanyName.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txt_CompanyName.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        panel_SearchByCompanyName.add(txt_CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 800, 40));

        btn_Searchbtn.setBackground(new java.awt.Color(51, 204, 255));
        btn_Searchbtn.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btn_Searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        btn_Searchbtn.setText("ค้นหา");
        btn_Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchbtnActionPerformed(evt);
            }
        });
        panel_SearchByCompanyName.add(btn_Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 303, 800, 60));

        getContentPane().add(panel_SearchByCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 860, 540));

        panel_SearchByJobType.setBackground(new java.awt.Color(255, 255, 255));
        panel_SearchByJobType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_SearchByJobType.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setBackground(new java.awt.Color(0, 204, 204));
        jLabel63.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("     ค้นหางานตามประเภทงาน");
        jLabel63.setOpaque(true);
        panel_SearchByJobType.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        jLabel7.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel7.setText(">> กฎหมาย\t   ");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel64.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel64.setText(">> นำเข้า/ ส่งออก/ Shipping");
        jLabel64.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel65.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel65.setText(">> Web Design/Graphic Design\t");
        jLabel65.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel66.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel66.setText(">> เจ้าหน้าที่ขาย-การตลาด / พนักงานขาย-การตลาด");
        jLabel66.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel67.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel67.setText(">> ประสานงานการขาย-การตลาด\t");
        jLabel67.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel67MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel68.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel68.setText(">> ผู้จัดการ/ผู้ช่วยผู้จัดการขาย-การตลาด");
        jLabel68.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel68MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel69.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel69.setText(">> งานการศึกษา/นักวิชาการ/อาจารย์");
        jLabel69.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel69.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel69MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel70.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel70.setText(">> ธุรการ/ประสานงาน/คีย์ข้อมูล\t ");
        jLabel70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel71.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel71.setText(">> เลขานุการ");
        jLabel71.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel71MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel72.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel72.setText(">> ประชาสัมพันธ์/บริการลูกค้า");
        jLabel72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel73.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel73.setText(">> บัญชี/การเงิน-การธนาคาร\t ");
        jLabel73.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel73MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel74.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel74.setText(">> บุคคล/ฝึกอบรม/Training");
        jLabel74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel74MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel75.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel75.setText(">> จัดซื้อ/คลังสินค้า/logistics");
        jLabel75.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel75MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel76.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel76.setText(">> เกษตร/ปศุสัตว์/ประมง/เหมืองแร่");
        jLabel76.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel76MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel77.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel77.setText(">> เศรษฐศาสตร์/สถิติ/งานวิจัย/หุ้น/การประกันภัย\t  ");
        jLabel77.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        jLabel78.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel78.setText(">> โรงงาน/การผลิต/ควบคุมคุณภาพ");
        jLabel78.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel78.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel78MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel79.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel79.setText(">> ช่างยนต์/ช่างกลโรงงาน/ช่างเทคนิคอุตสาหกรรม");
        jLabel79.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel79.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel79MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel80.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel80.setText(">> ช่างไฟฟ้า/ช่างอิเลกทรอนิกส์/ช่างโลหะ");
        jLabel80.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel80.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel80MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel81.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel81.setText(">> ช่างคอมพิวเตอร์/ช่างเทคนิคคอมพิวเตอร์");
        jLabel81.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel81.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel81MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel82.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel82.setText(">> ช่างจิวเวอร์รี่ /ช่างทอง-เงิน");
        jLabel82.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel82.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel82MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel83.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel83.setText(">> ดีไซด์เนอร์/ช่างตัดเย็บเสื้อผ้า/ช่างแพทเทิร์น");
        jLabel83.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel83MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel84.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel84.setText(">> โฟร์แมน/ช่างก่อสร้าง/ช่างไม้");
        jLabel84.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel84MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel85.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel85.setText(">> งานเขียนแบบ/ งานDrawing");
        jLabel85.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel85MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel86.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel86.setText(">> ศิลปะ/จิตรกรรม/ออกแบบผลิตภัณฑ์");
        jLabel86.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel86.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel86MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel87.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel87.setText(">> Programmer/System Admin/IT");
        jLabel87.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel87.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel87MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel88.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel88.setText(">> Web programmer/Webmaster");
        jLabel88.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel88.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel88MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel89.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel89.setText(">> งานด้านต่างประเทศ");
        jLabel89.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel89.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel89MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        jLabel90.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel90.setText(">> วิศวกรเครื่องกล/โรงงาน/วิศวกรอุตสาหกรรม");
        jLabel90.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel90.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel90MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel91.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel91.setText(">> วิศวกรไฟฟ้า/วิศวกรอิเลกทรอนิกส์");
        jLabel91.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel91.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel91MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel92.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel92.setText(">> วิศวกรโยธา/วิศวกรก่อสร้าง");
        jLabel92.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel92.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel92MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel93.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel93.setText(">> วิศวกรสื่อสาร/โทรคมนาคม");
        jLabel93.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel93.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel93MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jLabel94.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel94.setText(">> งาน Part-time/นักศึกษาฝึกงาน");
        jLabel94.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel94.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel94MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jLabel95.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel95.setText(">> สถาปัตยกรรม/ออกแบบตกแต่ง/ประเมินราคา");
        jLabel95.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel95MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        jLabel96.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel96.setText(">> งานโฆษณา/ขายโฆษณา/Creative/ช่างภาพ");
        jLabel96.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel96.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel96MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel97.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel97.setText(">> งานบันเทิง/ นักแสดง/ พริ๊ตตี้/ นักดนตรี/ นักร้อง");
        jLabel97.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel97.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel97MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jLabel98.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel98.setText(">> สุขภาพความงาม/เสริมสวย/สปา/ฟิตเนส");
        jLabel98.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel98.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel98MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel99.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel99.setText(">> ผู้จัดการทั่วไป/ผู้อำนวยการ/งานผู้บริหาร");
        jLabel99.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel99.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel99MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel100.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel100.setText(">> พัฒนาธุรกิจ/พัฒนาองค์กร ISO");
        jLabel100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel100MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 20));

        jLabel101.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel101.setText(">> วิศวกรขาย/Sale Engineer");
        jLabel101.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel101MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel102.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel102.setText(">> นักข่าว/บรรณาธิการ/นักเขียน/แปลภาษา");
        jLabel102.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel102MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        jLabel103.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel103.setText(">> การโรงแรม/ล่าม/ไกด์/มัคคุเทศก์/งานท่องเที่ยว");
        jLabel103.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel103MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jLabel104.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel104.setText(">> งานบริการทั่วไป/บริกร/พนักงานเสิร์ฟ");
        jLabel104.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel104MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel105.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel105.setText(">> งานด้านอาหาร-เครื่องดื่ม/กุ๊ก/บาร์เทนเดอร์");
        jLabel105.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel105MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        jLabel106.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel106.setText(">> วิศวกรคอมพิวเตอร์/วิศวกรระบบ");
        jLabel106.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel106MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jLabel107.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel107.setText(">> แพทย์/พยาบาล/เภสัช");
        jLabel107.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel107.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel107MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jLabel108.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel108.setText(">> วิทยาศาสตร์อาหาร/โภชนาการ");
        jLabel108.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel108.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel108MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jLabel109.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel109.setText(">> วิทยาศาสตร์/เคมี/ชีวะ/สิ่งแวดล้อม/ภูมิศาสตร์\t");
        jLabel109.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel109.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel109MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabel110.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel110.setText(">> ส่งเอกสาร/ส่งผลิตภัณฑ์/ขับรถ/แม่บ้าน/รปภ.");
        jLabel110.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel110.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel110MouseClicked(evt);
            }
        });
        panel_SearchByJobType.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        getContentPane().add(panel_SearchByJobType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 860, 540));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("ค้นหางานตามชื่องาน");
        jLabel58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 40));

        jLabel59.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("ค้นหางานตามประเภท");
        jLabel59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -2, -1, 40));

        btn_disconnect.setBackground(new java.awt.Color(0, 0, 102));
        btn_disconnect.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        btn_disconnect.setForeground(new java.awt.Color(255, 255, 255));
        btn_disconnect.setText("ออกจากระบบ");
        btn_disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disconnectActionPerformed(evt);
            }
        });
        jPanel2.add(btn_disconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 860, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        panel_SearchByJobType.setVisible(true);
        panel_SearchByCompanyName.setVisible(false);
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        panel_SearchByJobType.setVisible(false);
        panel_SearchByCompanyName.setVisible(true);
    }//GEN-LAST:event_jLabel58MouseClicked

    private void btn_SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchbtnActionPerformed
        jobList.listJob(txt_CompanyName.getText(), "ByJobName");
        jobList.show();
    }//GEN-LAST:event_btn_SearchbtnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        jobList.listJob("กฎหมาย", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        jobList.listJob("นำเข้า/ ส่งออก/ Shipping", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        jobList.listJob("Web Design/Graphic Design", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        jobList.listJob("เจ้าหน้าที่ขาย-การตลาด / พนักงานขาย-การตลาด", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel66MouseClicked

    private void jLabel67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseClicked
        jobList.listJob("ประสานงานการขาย-การตลาด", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel67MouseClicked

    private void jLabel68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseClicked
        jobList.listJob("ผู้จัดการ/ผู้ช่วยผู้จัดการขาย-การตลาด\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel68MouseClicked

    private void jLabel69MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel69MouseClicked
        jobList.listJob("งานการศึกษา/นักวิชาการ/อาจารย์", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel69MouseClicked

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
        jobList.listJob("ธุรการ/ประสานงาน/คีย์ข้อมูล\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel70MouseClicked

    private void jLabel71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseClicked
        jobList.listJob("เลขานุการ\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel71MouseClicked

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        jobList.listJob("ประชาสัมพันธ์/บริการลูกค้า", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel72MouseClicked

    private void jLabel73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel73MouseClicked
        jobList.listJob("บัญชี/การเงิน-การธนาคาร\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel73MouseClicked

    private void jLabel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseClicked
        jobList.listJob("บุคคล/ฝึกอบรม/Training\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel74MouseClicked

    private void jLabel75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel75MouseClicked
        jobList.listJob("จัดซื้อ/คลังสินค้า/logistics", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel75MouseClicked

    private void jLabel76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseClicked
        jobList.listJob("เกษตร/ปศุสัตว์/ประมง/เหมืองแร่\t  ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel76MouseClicked

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
        jobList.listJob("เศรษฐศาสตร์/สถิติ/งานวิจัย/หุ้น/การประกันภัย  ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel77MouseClicked

    private void jLabel78MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseClicked
        jobList.listJob("โรงงาน/การผลิต/ควบคุมคุณภาพ\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel78MouseClicked

    private void jLabel79MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel79MouseClicked
        jobList.listJob("ช่างยนต์/ช่างกลโรงงาน/ช่างเทคนิคอุตสาหกรรม", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel79MouseClicked

    private void jLabel80MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel80MouseClicked
        jobList.listJob("ช่างไฟฟ้า/ช่างอิเลกทรอนิกส์/ช่างโลหะ\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel80MouseClicked

    private void jLabel81MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel81MouseClicked
        jobList.listJob("ช่างคอมพิวเตอร์/ช่างเทคนิคคอมพิวเตอร์\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel81MouseClicked

    private void jLabel82MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel82MouseClicked
        jobList.listJob("ช่างจิวเวอร์รี่ /ช่างทอง-เงิน", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel82MouseClicked

    private void jLabel83MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel83MouseClicked
        jobList.listJob("ดีไซด์เนอร์/ช่างตัดเย็บเสื้อผ้า/ช่างแพทเทิร์น\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel83MouseClicked

    private void jLabel84MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel84MouseClicked
        jobList.listJob("โฟร์แมน/ช่างก่อสร้าง/ช่างไม้", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel84MouseClicked

    private void jLabel85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel85MouseClicked
        jobList.listJob("งานเขียนแบบ/ งานDrawing", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel85MouseClicked

    private void jLabel86MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel86MouseClicked
        jobList.listJob("ศิลปะ/จิตรกรรม/ออกแบบผลิตภัณฑ์\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel86MouseClicked

    private void jLabel87MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel87MouseClicked
        jobList.listJob("Programmer/System Admin/IT\t ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel87MouseClicked

    private void jLabel88MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel88MouseClicked
        jobList.listJob("Web programmer/Webmaster", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel88MouseClicked

    private void jLabel89MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel89MouseClicked
        jobList.listJob("งานด้านต่างประเทศ\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel89MouseClicked

    private void jLabel90MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel90MouseClicked
        jobList.listJob("วิศวกรเครื่องกล/โรงงาน/วิศวกรอุตสาหกรรม", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel90MouseClicked

    private void jLabel91MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel91MouseClicked
        jobList.listJob("วิศวกรไฟฟ้า/วิศวกรอิเลกทรอนิกส์\t  ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel91MouseClicked

    private void jLabel92MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel92MouseClicked
        jobList.listJob("วิศวกรโยธา/วิศวกรก่อสร้าง\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel92MouseClicked

    private void jLabel93MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel93MouseClicked
        jobList.listJob("วิศวกรสื่อสาร/โทรคมนาคม", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel93MouseClicked

    private void jLabel94MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel94MouseClicked
        jobList.listJob("งาน Part-time/นักศึกษาฝึกงาน", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel94MouseClicked

    private void jLabel95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel95MouseClicked
        jobList.listJob("สถาปัตยกรรม/ออกแบบตกแต่ง/ประเมินราคา\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel95MouseClicked

    private void jLabel96MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel96MouseClicked
        jobList.listJob("งานโฆษณา/ขายโฆษณา/Creative/ช่างภาพ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel96MouseClicked

    private void jLabel97MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel97MouseClicked
        jobList.listJob("งานบันเทิง/ นักแสดง/ พริ๊ตตี้/ นักดนตรี/ นักร้อง  ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel97MouseClicked

    private void jLabel98MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel98MouseClicked
        jobList.listJob("สุขภาพความงาม/เสริมสวย/สปา/ฟิตเนส\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel98MouseClicked

    private void jLabel99MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel99MouseClicked
        jobList.listJob("ผู้จัดการทั่วไป/ผู้อำนวยการ/งานผู้บริหาร", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel99MouseClicked

    private void jLabel100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel100MouseClicked
        jobList.listJob("พัฒนาธุรกิจ/พัฒนาองค์กร ISO", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel100MouseClicked

    private void jLabel101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel101MouseClicked
        jobList.listJob("วิศวกรขาย/Sale Engineer", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel101MouseClicked

    private void jLabel102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel102MouseClicked
        jobList.listJob("นักข่าว/บรรณาธิการ/นักเขียน/แปลภาษา", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel102MouseClicked

    private void jLabel103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel103MouseClicked
        jobList.listJob("การโรงแรม/ล่าม/ไกด์/มัคคุเทศก์/งานท่องเที่ยว ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel103MouseClicked

    private void jLabel104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel104MouseClicked
        jobList.listJob("งานบริการทั่วไป/บริกร/พนักงานเสิร์ฟ\t  ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel104MouseClicked

    private void jLabel105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel105MouseClicked
        jobList.listJob("งานด้านอาหาร-เครื่องดื่ม/กุ๊ก/บาร์เทนเดอร์", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel105MouseClicked

    private void jLabel106MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel106MouseClicked
        jobList.listJob("วิศวกรคอมพิวเตอร์/วิศวกรระบบ ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel106MouseClicked

    private void jLabel107MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel107MouseClicked
        jobList.listJob("แพทย์/พยาบาล/เภสัช\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel107MouseClicked

    private void jLabel108MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel108MouseClicked
        jobList.listJob("วิทยาศาสตร์อาหาร/โภชนาการ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel108MouseClicked

    private void jLabel109MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel109MouseClicked
        jobList.listJob("วิทยาศาสตร์/เคมี/ชีวะ/สิ่งแวดล้อม/ภูมิศาสตร์\t  ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel109MouseClicked

    private void jLabel110MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel110MouseClicked
        jobList.listJob("ส่งเอกสาร/ส่งผลิตภัณฑ์/ขับรถ/แม่บ้าน/รปภ.\t   ", "ByJobType");
        jobList.show();
    }//GEN-LAST:event_jLabel110MouseClicked

    private void btn_disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disconnectActionPerformed
        userMainService.logout();
        LoginForm login = new LoginForm();
        login.show();
        hide();
    }//GEN-LAST:event_btn_disconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        System.out.println("FormUser.main()");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Searchbtn;
    private javax.swing.JButton btn_disconnect;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_SearchByCompanyName;
    private javax.swing.JPanel panel_SearchByJobType;
    private javax.swing.JTextField txt_CompanyName;
    // End of variables declaration//GEN-END:variables
}
